image: Visual Studio 2017

configuration: Release

build:
  project: Source/RetryableAssertions.sln
  publish_nuget: true
  verbosity: minimal

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: kzcvJAzD0KU9cwRrF0tFd78Nd62jQxuQxOwoaaacfA+llShhmzxLdr8+Jgnu9BZm
    skip_symbols: true
    on:
      branch: /^master$/